sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.11,<2.0"
  - DJANGO_VERSION="Django>=2.0,<2.1"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  - "3.6"
before_script:
  - pip install coverage coveralls
  - pip install -q "$DJANGO_VERSION"
  - python setup.py install
script:
  - coverage run manage.py test --settings=test_settings
after_script:
  - coveralls
matrix:
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
